"""added settings

Revision ID: e0ea4a7d57a8
Revises: 7f12ab9d31ac
Create Date: 2018-02-14 21:41:39.585924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ea4a7d57a8'
down_revision = '7f12ab9d31ac'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subby_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tracked_topics', sa.Boolean(), nullable=False),
    sa.Column('email', sa.Boolean(), nullable=False),
    sa.Column('rss_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subby_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_subby_settings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subby_settings')
    # ### end Alembic commands ###
