"""initial revision

Revision ID: 7f12ab9d31ac
Revises: 
Create Date: 2018-02-14 15:20:44.030344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f12ab9d31ac'
down_revision = None
branch_labels = ('subby',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subby_subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forum_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forum_id'], ['forums.id'], name=op.f('fk_subby_subscriptions_forum_id_forums'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subby_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'forum_id', name=op.f('pk_subby_subscriptions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subby_subscriptions')
    # ### end Alembic commands ###
